import { BackButton } from '@/components/ui/back-button';
import { setRequestLocale } from 'next-intl/server';

type Props = {
    params: Promise<{ locale: string }>;
};

export default async function DisclaimerPage({ params }: Props) {
    const { locale } = await params;
    setRequestLocale(locale);

    return (
        <main className="min-h-screen bg-background">
            <div className="container mx-auto px-4 lg:px-8 py-12 max-w-4xl">
                <BackButton label={locale === 'fr' ? 'Retour' : 'Back'} />

                <article className="prose prose-invert prose-sm max-w-none [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:mb-2 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-3 [&_p]:text-muted-foreground [&_p]:mb-4 [&_p]:leading-relaxed [&_ul]:text-muted-foreground [&_ul]:mb-4 [&_ul]:space-y-2 [&_li]:leading-relaxed [&_ol]:text-muted-foreground [&_ol]:mb-4 [&_ol]:space-y-2 [&_strong]:text-foreground [&_a]:text-primary [&_a]:hover:underline [&_hr]:border-border [&_hr]:my-12">
                    {/* ========== FRENCH ========== */}
                    <h1>Avertissement important</h1>

                    <p>
                        Les contenus propos&eacute;s sur le site iaco.app, au sein du programme Challenge 14 jours, ainsi que les r&eacute;ponses g&eacute;n&eacute;r&eacute;es par l&apos;assistant conversationnel Iaco, sont fournis exclusivement &agrave; des fins p&eacute;dagogiques et informatives.
                    </p>
                    <p>
                        Iaco ne fournit aucun conseil en investissement, aucun conseil financier personnalis&eacute;, ni aucune recommandation d&apos;achat ou de vente d&apos;actifs financiers ou de crypto-actifs.
                    </p>

                    <p>Les informations diffus&eacute;es :</p>
                    <ul>
                        <li>ne constituent pas une recommandation d&apos;investissement au sens de la r&eacute;glementation applicable ;</li>
                        <li>ne tiennent pas compte de la situation personnelle, patrimoniale ou financi&egrave;re de l&apos;utilisateur ;</li>
                        <li>ne garantissent aucun rendement ni aucune performance future.</li>
                    </ul>

                    <p>
                        <strong>Les march&eacute;s financiers et les crypto-actifs pr&eacute;sentent un risque &eacute;lev&eacute; de perte en capital, pouvant aller jusqu&apos;&agrave; la perte totale des sommes investies.</strong>
                    </p>
                    <p>
                        Toute d&eacute;cision d&apos;investissement rel&egrave;ve de la seule responsabilit&eacute; de l&apos;utilisateur.
                    </p>
                    <p>
                        Il appartient &agrave; chacun de r&eacute;aliser ses propres analyses et, le cas &eacute;ch&eacute;ant, de consulter un conseiller financier ou un professionnel habilit&eacute; avant toute d&eacute;cision d&apos;investissement.
                    </p>
                    <p>
                        Iaco d&eacute;cline toute responsabilit&eacute; quant aux d&eacute;cisions prises sur la base des informations fournies sur la plateforme.
                    </p>

                    <hr />

                    {/* ========== ENGLISH ========== */}
                    <h1>Important Notice</h1>

                    <p>
                        The content available on iaco.app, within the 14-Day Challenge program, and the responses generated by the Iaco conversational assistant are provided solely for educational and informational purposes.
                    </p>
                    <p>
                        Iaco does not provide investment advice, financial advice, or personalized recommendations regarding the purchase or sale of financial instruments or crypto-assets.
                    </p>

                    <p>The information provided:</p>
                    <ul>
                        <li>does not constitute investment advice under applicable regulations;</li>
                        <li>does not take into account the user&apos;s personal financial situation;</li>
                        <li>does not guarantee any return or future performance.</li>
                    </ul>

                    <p>
                        <strong>Financial markets and crypto-assets involve a high risk of capital loss, including the total loss of invested funds.</strong>
                    </p>
                    <p>
                        Any investment decision remains solely the responsibility of the user.
                    </p>
                    <p>
                        Users are encouraged to conduct their own research and, if necessary, consult a licensed financial advisor before making any investment decision.
                    </p>
                    <p>
                        Iaco disclaims any liability for decisions made based on the information provided on the platform.
                    </p>
                </article>
            </div>
        </main>
    );
}
